merge from trunk

diff --git a/dso/branches/session2forge/code/base/tcbuild b/dso/branches/session2forge/code/base/tcbuild
--- a/dso/branches/session2forge/code/base/tcbuild
+++ b/dso/branches/session2forge/code/base/tcbuild
@@ -1,29 +1,45 @@
 #!/bin/sh
 
-#if test ! -f build-tc.rb; then
-#	echo "$0: No 'build-tc.rb' script found. Run this from a directory with a valid 'build-tc.rb' script."
-#fi
-
 if test -z "${JAVA_HOME}"; then
-	JAVA_HOME="${TC_JAVA_HOME_15}"
-	export JAVA_HOME
+	echo "JAVA_HOME is not set"
+  exit 1
 fi
 
-JRUBY_HOME="`dirname $0`/../../buildsystems/jruby-1.1.2-20081015"
+if test -z "${ANT_HOME}"; then
+	echo "ANT_HOME is not set"
+  exit 1
+fi
+
+jruby_version=jruby-1.1.2-20090208
+build_system_dir=`dirname $0`/../../buildsystems
+cache_dir=$HOME/.tc
+if [ `uname | grep CYGWIN` ]; then
+  cache_dir=c:/temp/tc
+fi
+
+if [ ! -d "$cache_dir" ]; then
+  mkdir -p $cache_dir
+fi  
+
+JRUBY_HOME="$cache_dir/$jruby_version"
 export JRUBY_HOME
 
-"${ANT_HOME}/bin/ant" -buildfile "`dirname $0`/buildconfig/build.xml" install-ivy
-
-if test ! -d "${JRUBY_HOME}"; then
-	echo "--------------------------------------------------------------------------------"
-	echo "LOADING JRUBY USING IVY"
-	echo ""
-	"${ANT_HOME}/bin/ant" -buildfile "`dirname $0`/buildconfig/build.xml"
+# to be removed
+if [ -d "$build_system_dir/$jruby_version" ]; then
+  if [ ! -d $JRUBY_HOME ]; then
+    echo "moving jruby to a new cache $cache_dir. This only done once."
+    banner WAIT
+    mv "$build_system_dir/$jruby_version" "$cache_dir"
+  fi
 fi
 
+if [ ! -d "${JRUBY_HOME}" ]; then
+  echo "JRuby not found at $JRUBY_HOME. Installing..."
+	"${ANT_HOME}/bin/ant" -buildfile "$build_system_dir/install-jruby-build.xml"
+fi
 
-	echo ""
-	echo "--------------------------------------------------------------------------------"
-	echo "RUNNING TCBUILD"
-	echo ""
-	exec /bin/bash "${JRUBY_HOME}/bin/jruby" -Ibuildscripts buildscripts/build-tc.rb "$@"
+echo ""
+echo "--------------------------------------------------------------------------------"
+echo "RUNNING TCBUILD"
+echo ""
+exec /bin/bash "${JRUBY_HOME}/bin/jruby" -Ibuildscripts buildscripts/build-tc.rb "$@"
